markdown: rdiscount
rdiscount:
  extensions: [smart]

highlighter: pygments

permalink: /:year/:month/:title/
paginate: 5

title: Development, design, and more by Alec Reynolds
author: Alec Reynolds
email: hello@reynoldsalec.github.io
description: Alec Reynolds is a Front End Developer from Columbus, OH
url: http://reynoldsalec.github.io

exclude: ['config.json', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '*.scss']

show_drafts: true

suggested_tweet:
  related: ['davidensinger']
