markdown: rdiscount
rdiscount:
  extensions: [smart]

highlighter: pygments

permalink: /:year/:month/:title/
paginate: 5

title: Living Better, Together
author: Alec Reynolds
email: hello@reynoldsalec.github.io
description: Alec Reynolds is a civic entrepreneur from Oakland, CA
url: http://reynoldsalec.github.io

exclude: ['config.json', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '*.scss']

show_drafts: true

suggested_tweet:
  related: ['reynoldsalec']
